[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["ssr", "tokio"] }